services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    network_mode: host
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow --default-artifact-root /mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow
    environment:
      - MLFLOW_ALLOW_DNS_REBINDING=true
    user: "root"
  app:
    build: .
    network_mode: host
    volumes:
      - ./src:/app/src
      - ./datasets:/app/data
      - ./logs:/app/logs
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - POLARS_MAX_THREADS=2
    command: >
      sh -c "python src/bronze_loader.py &&
             python src/silver_transform.py &&
             python src/gold_process.py &&
             python src/ml_train.py"